"""Preloaded catalog of popular enterprise SaaS applications."""

SEED_APPS = [
    {
        "slug": "slack",
        "name": "Slack",
        "tagline": "Where work happens",
        "category": "Communication",
        "logo_url": "https://logo.clearbit.com/slack.com",
        "website": "https://slack.com",
        "description": "Slack is a messaging app for business that connects people to the information they need. It brings teams together to work as one unified group with channels, huddles, and thousands of app integrations.",
        "rating": 4.7,
        "reviews_count": 42150,
        "installs": "12M+",
        "pricing": "Freemium",
        "status": "Integrated",
        "verified": True,
        "tags": ["Messaging", "Team Chat", "Collaboration", "Huddles"],
        "features": [
            "Organized channels for every project and team",
            "Audio & video huddles for quick sync-ups",
            "2,600+ app integrations and workflow automation",
            "Enterprise-grade security with SOC 2 & GDPR compliance",
            "Powerful search across all conversations and files",
        ],
        "compliance": ["SOC 2", "GDPR", "ISO 27001", "HIPAA"],
    },
    {
        "slug": "notion",
        "name": "Notion",
        "tagline": "One workspace. Every team.",
        "category": "Productivity",
        "logo_url": "https://logo.clearbit.com/notion.so",
        "website": "https://notion.so",
        "description": "Notion is the connected workspace where better, faster work happens. Combine notes, docs, wikis, and project management into a single, flexible tool your whole team can customize.",
        "rating": 4.8,
        "reviews_count": 38900,
        "installs": "30M+",
        "pricing": "Freemium",
        "status": "Available",
        "verified": True,
        "tags": ["Docs", "Wiki", "Notes", "Project Management"],
        "features": [
            "Flexible docs, wikis, and databases in one place",
            "Notion AI to write, summarize, and brainstorm",
            "Customizable templates for any workflow",
            "Real-time collaboration with comments and mentions",
            "Powerful relational databases and views",
        ],
        "compliance": ["SOC 2", "GDPR", "ISO 27001"],
    },
    {
        "slug": "figma",
        "name": "Figma",
        "tagline": "Design and build together",
        "category": "Design",
        "logo_url": "https://logo.clearbit.com/figma.com",
        "website": "https://figma.com",
        "description": "Figma is the collaborative interface design tool that brings teams together to design, prototype, and gather feedback all in one place, right in the browser.",
        "rating": 4.9,
        "reviews_count": 51200,
        "installs": "20M+",
        "pricing": "Freemium",
        "status": "Available",
        "verified": True,
        "tags": ["UI Design", "Prototyping", "Whiteboard", "Collaboration"],
        "features": [
            "Real-time multiplayer design collaboration",
            "Interactive prototyping and dev handoff",
            "FigJam online whiteboard for brainstorming",
            "Reusable components and design systems",
            "Auto layout and advanced vector editing",
        ],
        "compliance": ["SOC 2", "GDPR"],
    },
    {
        "slug": "github",
        "name": "GitHub",
        "tagline": "Where the world builds software",
        "category": "DevOps",
        "logo_url": "https://logo.clearbit.com/github.com",
        "website": "https://github.com",
        "description": "GitHub is the complete developer platform to build, scale, and deliver secure software. Host and review code, manage projects, and ship with CI/CD and Copilot.",
        "rating": 4.8,
        "reviews_count": 64300,
        "installs": "100M+",
        "pricing": "Freemium",
        "status": "Integrated",
        "verified": True,
        "tags": ["Version Control", "CI/CD", "Code Review", "Copilot"],
        "features": [
            "Git-based version control and pull requests",
            "GitHub Actions for CI/CD automation",
            "GitHub Copilot AI pair programmer",
            "Advanced security and code scanning",
            "Project boards and issue tracking",
        ],
        "compliance": ["SOC 2", "GDPR", "ISO 27001"],
    },
    {
        "slug": "stripe",
        "name": "Stripe",
        "tagline": "Financial infrastructure for the internet",
        "category": "Finance",
        "logo_url": "https://logo.clearbit.com/stripe.com",
        "website": "https://stripe.com",
        "description": "Stripe is a suite of payment APIs that powers commerce for online businesses of all sizes, including fraud prevention, subscription management, and global payouts.",
        "rating": 4.7,
        "reviews_count": 29800,
        "installs": "4M+",
        "pricing": "Paid",
        "status": "Available",
        "verified": True,
        "tags": ["Payments", "Billing", "Subscriptions", "API"],
        "features": [
            "Accept payments in 135+ currencies",
            "Subscription and recurring billing",
            "Radar machine-learning fraud protection",
            "Detailed financial reporting and reconciliation",
            "Developer-first APIs and SDKs",
        ],
        "compliance": ["PCI DSS", "SOC 2", "GDPR"],
    },
    {
        "slug": "hubspot",
        "name": "HubSpot",
        "tagline": "Grow better with the customer platform",
        "category": "CRM & Sales",
        "logo_url": "https://logo.clearbit.com/hubspot.com",
        "website": "https://hubspot.com",
        "description": "HubSpot is a customer platform with all the software, integrations, and resources you need to connect marketing, sales, content management, and customer service.",
        "rating": 4.5,
        "reviews_count": 21400,
        "installs": "200K+",
        "pricing": "Freemium",
        "status": "Available",
        "verified": True,
        "tags": ["CRM", "Marketing", "Sales", "Automation"],
        "features": [
            "Unified CRM for contacts and deals",
            "Marketing automation and email campaigns",
            "Sales pipeline and forecasting tools",
            "Customer service ticketing and knowledge base",
            "AI-powered content and reporting",
        ],
        "compliance": ["SOC 2", "GDPR", "ISO 27001"],
    },
    {
        "slug": "datadog",
        "name": "Datadog",
        "tagline": "Modern monitoring & security",
        "category": "Analytics",
        "logo_url": "https://logo.clearbit.com/datadoghq.com",
        "website": "https://datadoghq.com",
        "description": "Datadog is the observability platform for cloud-scale applications, providing monitoring of servers, databases, tools, and services through a SaaS-based data analytics platform.",
        "rating": 4.6,
        "reviews_count": 15600,
        "installs": "30K+",
        "pricing": "Paid",
        "status": "Available",
        "verified": True,
        "tags": ["Monitoring", "Observability", "APM", "Logs"],
        "features": [
            "Infrastructure and application performance monitoring",
            "Real-time log management and analytics",
            "Distributed tracing across microservices",
            "Custom dashboards and alerting",
            "Security monitoring and threat detection",
        ],
        "compliance": ["SOC 2", "GDPR", "ISO 27001", "HIPAA"],
    },
    {
        "slug": "salesforce",
        "name": "Salesforce",
        "tagline": "The #1 AI CRM",
        "category": "CRM & Sales",
        "logo_url": "https://logo.clearbit.com/salesforce.com",
        "website": "https://salesforce.com",
        "description": "Salesforce is the world's leading cloud-based CRM platform, helping companies connect with customers through sales, service, marketing, and analytics clouds powered by Einstein AI.",
        "rating": 4.4,
        "reviews_count": 33700,
        "installs": "150K+",
        "pricing": "Enterprise",
        "status": "Available",
        "verified": True,
        "tags": ["CRM", "Sales Cloud", "Einstein AI", "Analytics"],
        "features": [
            "360-degree customer view across teams",
            "Einstein AI predictions and recommendations",
            "Customizable workflows and automation",
            "AppExchange marketplace of integrations",
            "Advanced analytics and reporting",
        ],
        "compliance": ["SOC 2", "GDPR", "ISO 27001", "HIPAA"],
    },
    {
        "slug": "zendesk",
        "name": "Zendesk",
        "tagline": "Champions of customer service",
        "category": "Communication",
        "logo_url": "https://logo.clearbit.com/zendesk.com",
        "website": "https://zendesk.com",
        "description": "Zendesk is a service-first CRM company that builds software designed to improve customer relationships with support, sales, and customer engagement tools.",
        "rating": 4.3,
        "reviews_count": 18200,
        "installs": "100K+",
        "pricing": "Paid",
        "status": "Available",
        "verified": True,
        "tags": ["Support", "Help Desk", "Ticketing", "Live Chat"],
        "features": [
            "Omnichannel ticketing system",
            "AI-powered answer bot and automation",
            "Live chat and messaging",
            "Self-service help center",
            "Analytics and performance dashboards",
        ],
        "compliance": ["SOC 2", "GDPR", "ISO 27001"],
    },
    {
        "slug": "postman",
        "name": "Postman",
        "tagline": "The API platform",
        "category": "DevOps",
        "logo_url": "https://logo.clearbit.com/postman.com",
        "website": "https://postman.com",
        "description": "Postman is an API platform for building and using APIs. It simplifies each step of the API lifecycle and streamlines collaboration so you can create better APIs faster.",
        "rating": 4.6,
        "reviews_count": 24100,
        "installs": "25M+",
        "pricing": "Freemium",
        "status": "Integrated",
        "verified": True,
        "tags": ["API", "Testing", "Documentation", "Mock Servers"],
        "features": [
            "Design, test, and document APIs",
            "Automated API testing and monitoring",
            "Mock servers for development",
            "Team collaboration on API collections",
            "Public API network with 100K+ APIs",
        ],
        "compliance": ["SOC 2", "GDPR"],
    },
    {
        "slug": "jira",
        "name": "Jira",
        "tagline": "Plan, track, and release great software",
        "category": "Productivity",
        "logo_url": "https://logo.clearbit.com/atlassian.com",
        "website": "https://www.atlassian.com/software/jira",
        "description": "Jira is the #1 agile project management tool used by teams to plan, track, release, and support world-class software with confidence using Scrum and Kanban boards.",
        "rating": 4.4,
        "reviews_count": 27500,
        "installs": "10M+",
        "pricing": "Freemium",
        "status": "Available",
        "verified": True,
        "tags": ["Agile", "Scrum", "Kanban", "Issue Tracking"],
        "features": [
            "Scrum and Kanban boards for agile teams",
            "Customizable workflows and automation",
            "Roadmaps and sprint planning",
            "Detailed reporting and burndown charts",
            "Deep integration with the Atlassian suite",
        ],
        "compliance": ["SOC 2", "GDPR", "ISO 27001"],
    },
    {
        "slug": "loom",
        "name": "Loom",
        "tagline": "Async video messaging for work",
        "category": "Communication",
        "logo_url": "https://logo.clearbit.com/loom.com",
        "website": "https://loom.com",
        "description": "Loom is the async video messaging tool that helps you get your message across through instantly shareable videos, reducing meetings and speeding up communication.",
        "rating": 4.7,
        "reviews_count": 12800,
        "installs": "25M+",
        "pricing": "Freemium",
        "status": "Available",
        "verified": True,
        "tags": ["Screen Recording", "Video", "Async", "Sharing"],
        "features": [
            "One-click screen and camera recording",
            "Instantly shareable video links",
            "AI-generated titles, summaries, and chapters",
            "Viewer engagement insights",
            "Comments and emoji reactions",
        ],
        "compliance": ["SOC 2", "GDPR"],
    },
    {
        "slug": "zoom",
        "name": "Zoom",
        "tagline": "One platform to connect",
        "category": "Communication",
        "logo_url": "https://logo.clearbit.com/zoom.us",
        "website": "https://zoom.us",
        "description": "Zoom is a unified communications platform offering video meetings, team chat, phone, whiteboard, and an AI Companion to keep teams connected from anywhere.",
        "rating": 4.5,
        "reviews_count": 45600,
        "installs": "300M+",
        "pricing": "Freemium",
        "status": "Integrated",
        "verified": True,
        "tags": ["Video Meetings", "Webinars", "Phone", "AI Companion"],
        "features": [
            "HD video and audio meetings",
            "AI Companion for meeting summaries",
            "Team chat and phone system",
            "Webinars and large-scale events",
            "Virtual whiteboard collaboration",
        ],
        "compliance": ["SOC 2", "GDPR", "HIPAA"],
    },
    {
        "slug": "vercel",
        "name": "Vercel",
        "tagline": "Build and deploy on the AI Cloud",
        "category": "DevOps",
        "logo_url": "https://logo.clearbit.com/vercel.com",
        "website": "https://vercel.com",
        "description": "Vercel is the platform for frontend developers, providing the speed and reliability innovators need to create at the moment of inspiration with instant global deployment.",
        "rating": 4.8,
        "reviews_count": 14200,
        "installs": "1M+",
        "pricing": "Freemium",
        "status": "Available",
        "verified": True,
        "tags": ["Hosting", "Deployment", "Edge", "Next.js"],
        "features": [
            "Instant global deployments from Git",
            "Preview deployments for every push",
            "Edge network and serverless functions",
            "Built-in analytics and monitoring",
            "First-class Next.js support",
        ],
        "compliance": ["SOC 2", "GDPR"],
    },
    {
        "slug": "linear",
        "name": "Linear",
        "tagline": "The tool for modern software development",
        "category": "Productivity",
        "logo_url": "https://logo.clearbit.com/linear.app",
        "website": "https://linear.app",
        "description": "Linear is a purpose-built tool for planning and building products. Streamline issues, sprints, and product roadmaps with a fast, keyboard-first interface.",
        "rating": 4.9,
        "reviews_count": 9800,
        "installs": "500K+",
        "pricing": "Freemium",
        "status": "Available",
        "verified": True,
        "tags": ["Issue Tracking", "Sprints", "Roadmap", "Agile"],
        "features": [
            "Blazing-fast, keyboard-first interface",
            "Cycles for sprint planning",
            "Product roadmaps and projects",
            "Automated workflows and triage",
            "Git and Slack integrations",
        ],
        "compliance": ["SOC 2", "GDPR"],
    },
    {
        "slug": "framer",
        "name": "Framer",
        "tagline": "The website builder loved by designers",
        "category": "Design",
        "logo_url": "https://logo.clearbit.com/framer.com",
        "website": "https://framer.com",
        "description": "Framer is the web builder for stunning sites. Design and publish responsive websites with a canvas-based editor, CMS, and AI, no code required.",
        "rating": 4.7,
        "reviews_count": 11300,
        "installs": "2M+",
        "pricing": "Freemium",
        "status": "Available",
        "verified": True,
        "tags": ["Website Builder", "No-Code", "CMS", "Animations"],
        "features": [
            "Canvas-based visual website editor",
            "Built-in CMS for dynamic content",
            "AI-powered layout generation",
            "Advanced animations and interactions",
            "One-click publishing with hosting",
        ],
        "compliance": ["SOC 2", "GDPR"],
    },
]

# Governance / ownership metadata keyed by slug:
#   vendor           -> company that owns/provides the software
#   annual_cost      -> approximate financial cost per year (USD)
#   security_approved-> approved by Security/IT for organizational use
#   approved_by      -> approving authority
#   managed_by       -> internal team/owner responsible for the app
GOVERNANCE = {
    "slack": {"vendor": "Salesforce, Inc.", "annual_cost": 96000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "IT Operations"},
    "notion": {"vendor": "Notion Labs, Inc.", "annual_cost": 24000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "Knowledge Management"},
    "figma": {"vendor": "Figma, Inc. (Adobe)", "annual_cost": 18000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "Design Team"},
    "github": {"vendor": "GitHub, Inc. (Microsoft)", "annual_cost": 63000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "Engineering Platform"},
    "stripe": {"vendor": "Stripe, Inc.", "annual_cost": 0, "security_approved": True, "approved_by": "Security & IT", "managed_by": "Finance Engineering"},
    "hubspot": {"vendor": "HubSpot, Inc.", "annual_cost": 42000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "Marketing Ops"},
    "datadog": {"vendor": "Datadog, Inc.", "annual_cost": 120000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "SRE Team"},
    "salesforce": {"vendor": "Salesforce, Inc.", "annual_cost": 180000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "Revenue Operations"},
    "zendesk": {"vendor": "Zendesk, Inc.", "annual_cost": 55000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "Customer Support"},
    "postman": {"vendor": "Postman, Inc.", "annual_cost": 15000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "API Platform"},
    "jira": {"vendor": "Atlassian Corporation", "annual_cost": 38000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "Program Management"},
    "loom": {"vendor": "Atlassian Corporation", "annual_cost": 9000, "security_approved": False, "approved_by": "", "managed_by": "Internal Comms"},
    "zoom": {"vendor": "Zoom Video Communications", "annual_cost": 45000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "IT Operations"},
    "vercel": {"vendor": "Vercel, Inc.", "annual_cost": 28000, "security_approved": True, "approved_by": "Security & IT", "managed_by": "Frontend Platform"},
    "linear": {"vendor": "Linear Orbit, Inc.", "annual_cost": 12000, "security_approved": False, "approved_by": "", "managed_by": "Product Engineering"},
    "framer": {"vendor": "Framer B.V.", "annual_cost": 6000, "security_approved": False, "approved_by": "", "managed_by": "Marketing"},
}

for _app in SEED_APPS:
    _app.update(GOVERNANCE.get(_app["slug"], {}))
